-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	If the requested customer does not exist, reference the linkserver table to refresh local instance
--				updated data from iSeries				
-- =============================================
CREATE PROCEDURE getCustomer
	-- Add the parameters for the stored procedure here
	 @CustomerNum VARCHAR(7)
AS
BEGIN
SET NOCOUNT ON
	/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [CNUMBR]
      ,[CLNAME]
      ,[CAHEAD]
      ,[CSTRET]
      ,[CCTOWN]
      ,[CSTATE]
      ,[CZIP]
      ,[CSALSR]
      ,[CSRNAM]
      ,[CSRCTN]
      ,[CSMAIL]
      ,[CCTYCD]
      ,[CCNTRY]
      ,[CCONTY]
      ,[CTERRY]
      ,[CREGN]
      ,[CSTUS]
      ,[CCRSTS]
      ,[CCHIER]
      ,[CBILTO]
      ,[CSLTX#]
      ,[CSTEXP]
      ,[CSINST]
      ,[CSRRTN]
      ,[CSARTL]
      ,[CLPCD]
      ,[CLPPCT]
      ,[CLPDFT]
      ,[CLDFTP]
      ,[CLDFTA]
      ,[CSPCD]
      ,[CCPDSC]
      ,[CPMCD]
      ,[CSACST]
      ,[CSCRLM]
      ,[CSPORQ]
      ,[CSDSAC]
      ,[CSTXEM]
      ,[CSBACK]
      ,[CCOMDF]
      ,[CSSPLT]
      ,[CSISEQ]
      ,[CSACCD]
      ,[CSBLST]
      ,[CSSPEC]
      ,[CSBEST]
      ,[CSMNDV]
      ,[CSIVDP]
      ,[CSCHDP]
      ,[CSLSMN]
      ,[CSCMDP]
      ,[CSADD$]
      ,[CSTREG]
      ,[CSREXP]
      ,[CDEA#]
      ,[CDEEXP]
      ,[CSHIN#]
      ,[CLAB1]
      ,[CLAB2]
      ,[CSTXT1]
      ,[CSTXT2]
      ,[CSTXT3]
      ,[CSPHNA]
      ,[CSPHNE]
      ,[CSPHNN]
      ,[CSFAXA]
      ,[CSFAXE]
      ,[CSFAXN]
      ,[CSRCNM]
      ,[CSRCEX]
      ,[CSCHLD]
      ,[CVLCTY]
      ,[CSSTAX]
      ,[CSLTX1]
      ,[CSLTX2]
      ,[CSAUTP]
      ,[CSAUEX]
      ,[CSPSPW]
      ,[CSCAR#]
      ,[CSPREF]
      ,[CSLADT]
      ,[CTYPE]
      ,[CSBSTY]
      ,[CSACTY]
      ,[CSOMIT]
      ,[CBONLY]
      ,[C1IOD]
      ,[CSPHRM]
      ,[C1COD]
      ,[CSSUB]
      ,[CSRPCK]
      ,[CSREST]
      ,[CSDUPI]
      ,[CSSHPL]
      ,[CSPARS]
      ,[CSPRCL]
      ,[CARGL]
      ,[CSCDS#]
      ,[CSLBL#]
      ,[CSOID#]
      ,[CSROE#]
      ,[CSSDS#]
      ,[CREMIT]
      ,[CSANL1]
      ,[CSANL2]
      ,[CPRAWP]
      ,[CMSIFL]
      ,[CMSISR]
      ,[CSPCOC]
      ,[CSPDOC]
      ,[CSBLOC]
      ,[CSSRX]
      ,[CSSOTC]
      ,[CSRXSL]
      ,[CSOTSL]
      ,[CSGNSB]
      ,[CSGNPF]
      ,[CSGNDS]
      ,[CSBOMG]
      ,[CSEDI1]
      ,[CSEDI2]
      ,[CSLSDT]
      ,[CSOTSC]
      ,[CSOTPD]
      ,[CSRBTC]
      ,[CSSPDM]
      ,[CSEDII]
      ,[CSEDIP]
      ,[CSCONF]
      ,[CSCFDT]
      ,[CSMXLB]
      ,[CSMGRM]
      ,[CSSGRM]
  FROM [Foundation].[dbo].[FPCUSMAS]
WHERE @CustomerNum = dbo.FPCUSMAS.CNUMBR
   
END