CREATE TABLE [dbo].[FPITMBRS] (
    [IRITEM] DECIMAL (6) NULL,
    [IRWHSE] DECIMAL (2) NULL,
    [IRCTYP] DECIMAL (4) NULL,
    [IRQHRS] DECIMAL (7) NULL,
    [IRONLY] CHAR (1)    NULL,
    [IRBYLM] CHAR (1)    NULL
);

