CREATE TABLE [dbo].[FPLOCSUB] (
    [LSWHSE]   DECIMAL (2) NULL,
    [LSDAY]    DECIMAL (1) NULL,
    [LSDATE]   DECIMAL (7) NULL,
    [LSTIME]   DECIMAL (6) NULL,
    [LSROLWHS] DECIMAL (2) NULL
);

